# Generated by Django 5.2.17 on 2026-08-21 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('target_role', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parsed_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Cold Email'), ('linkedin', 'LinkedIn')], default='email', max_length=20)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('concise', 'Concise'), ('confident', 'Confident'), ('friendly', 'Friendly'), ('technical', 'Technical')], default='professional', max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_role', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_lines', models.JSONField(blank=True, default=list)),
                ('selected_subject', models.CharField(blank=True, max_length=300, null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_messages', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeJobAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suitability_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5)),
                ('skill_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('role_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('seniority_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('domain_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ats_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_call_probability_estimate', models.IntegerField(default=50)),
                ('ai_confidence', models.CharField(default='Medium', max_length=20)),
                ('matching_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_analyses', to='resumes.resume')),
            ],
            options={
                'ordering': ['-suitability_score'],
            },
        ),
        migrations.CreateModel(
            name='ResumeOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('potential_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('potential_improvement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('weak_sections', models.JSONField(blank=True, default=list)),
                ('suggested_improvements', models.JSONField(blank=True, default=list)),
                ('ats_formatting_concerns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_optimizations', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(default='other', max_length=50)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_skills', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('content_changes', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions', to='jobs.job')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_active'], name='resumes_res_user_id_7ea29c_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'target_role'], name='resumes_res_user_id_2f4250_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobanalysis',
            index=models.Index(fields=['job', 'suitability_score'], name='resumes_res_job_id_eaccc0_idx'),
        ),
        migrations.AddIndex(
            model_name='resumejobanalysis',
            index=models.Index(fields=['resume', 'job'], name='resumes_res_resume__cd361e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumejobanalysis',
            unique_together={('resume', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeskill',
            unique_together={('resume', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeversion',
            unique_together={('resume', 'version_number')},
        ),
    ]
