# Generated by Django 5.2.17 on 2026-08-21 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('hr_screening', 'HR Screening'), ('technical', 'Technical Round'), ('coding', 'Coding Challenge'), ('system_design', 'System Design'), ('managerial', 'Managerial Round'), ('hr', 'HR Round'), ('final', 'Final Round'), ('other', 'Other')], default='technical', max_length=30)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('interviewer', models.CharField(blank=True, max_length=150, null=True)),
                ('result', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['job', 'scheduled_at'], name='interviews__job_id_cdcce4_idx'), models.Index(fields=['result', 'scheduled_at'], name='interviews__result_74190b_idx')],
            },
        ),
    ]
