# Generated by Django 5.2.17 on 2026-08-21 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_role', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('current_ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_ctc_min', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_ctc_max', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_work_modes', models.JSONField(blank=True, default=list)),
                ('career_goal', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
