# Generated by Django 5.2.17 on 2026-08-21 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(db_index=True, max_length=100, unique=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Aliases',
                'ordering': ['canonical_name', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('cloud', 'Cloud'), ('testing', 'Testing'), ('ai_ml', 'AI / ML'), ('soft_skills', 'Soft Skills'), ('tools', 'Tools'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('course', 'Course'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'category'], name='skills_skil_user_id_d88ad4_idx'), models.Index(fields=['user', 'name'], name='skills_skil_user_id_c1981e_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
