# Generated by Django 5.2.17 on 2026-08-21 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('role', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='remote', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('experience_required', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('technical', 'Technical Round'), ('managerial', 'Managerial Round'), ('hr', 'HR Round'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], db_index=True, default='applied', max_length=30)),
                ('job_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw_description', models.TextField(blank=True, null=True)),
                ('match_score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'status'], name='jobs_job_user_id_ec4047_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'applied_date'], name='jobs_job_user_id_751bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'company'], name='jobs_job_user_id_db94b5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'role'], name='jobs_job_user_id_132ddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill_name')},
        ),
    ]
