# Generated by Django 5.2.17 on 2026-08-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_jobs', to='resumes.resume'),
        ),
    ]
